language: bash
services: docker

before_script:
   - docker info
   - docker images

script:
   - make

after_script:
   - docker images
   - docker run -dt --name=sinopia bankiru/sinopia:latest
   - sleep 5
   - docker logs sinopia
   - docker rm -f sinopia
